"""first migration

Revision ID: 992a9d7e06ac
Revises: 
Create Date: 2024-10-10 17:14:40.513770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '992a9d7e06ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__url'))
    )
    op.create_index(op.f('ix__url__id'), 'url', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__user'))
    )
    op.create_index(op.f('ix__user__id'), 'user', ['id'], unique=False)
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('pubdate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['url.id'], name=op.f('fk__news__url_id__url')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__news'))
    )
    op.create_index(op.f('ix__news__id'), 'news', ['id'], unique=False)
    op.create_table('users_urls',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['url.id'], name=op.f('fk__users_urls__url_id__url')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk__users_urls__user_id__user')),
    sa.PrimaryKeyConstraint('user_id', 'url_id', name=op.f('pk__users_urls'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_urls')
    op.drop_index(op.f('ix__news__id'), table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix__user__id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix__url__id'), table_name='url')
    op.drop_table('url')
    # ### end Alembic commands ###
